# -*- coding: utf-8 -*-

from random import choice

questions = [
    'Aan welk huishoudelijk klusje heb jij een grote hekel?',
    'Als je alle tijd van de wereld had, wat zou je dan doen?',
    'Als je de hele dag één gerecht moest eten, wat zou dat dan zijn?',
    'Als je deze week opnieuw kon doen, wat zou je anders doen',
    'Als je één ding uit je verleden kon aanpassen wat zou het dan zijn?',
    'Als je een eigen bedrijf zou starten, wat zou je dan verkopen?',
    'Als je een glazen bol had, wat zou je daar graag in willen zien?',
    'Als je iemand anders kon zijn, wie zou je dan willen zijn?',
    'Als je iets tegen de wereld zou kunnen zeggen, wat zou het zijn?',
    'Als je onsterfelijk zou zijn voor 1 dag, wat zou je dan doen?',
    'Als je terug in de tijd kon gaan, wat zou je dan doen?',
    'Als jij je eigen naam kon kiezen, hoe zou je dan heten?',
    'Ben je een pessimist of optimist?',
    'Ben je gelukkig?',
    'Ben je liever lang en dik, of klein en atletisch?',
    'Ben je liever populair of ben je liever slim?',
    'Ben je ooit naar de eerste hulp geweest?',
    'Ben jij een buiten - of een binnenmens?',
    'Ben jij een vroege vogel of een avondmens?',
    'Bij het spelen van welk spel verlies jij altijd?',
    'Bij welke film moest jij voor het laatst huilen?',
    'Denk je dat er op een dag buitenaardse wezens landen?',
    'Ga je liever naar de zon of naar de sneeuw?',
    'Geloof je in liefde op het eerste gezicht?',
    'Heb je afgelopen week iets nieuws geleerd?',
    'Heb je een stopwoord?',
    'Heb je liever een jaar geen tv of een jaar geen snacks?',
    'Heb je liever je grootste vraag beantwoord of je grootste wens vervuld?',
    'Heb je ooit iets gedaan waarmee je in de problemen kwam?',
    'Heb je vandaag een complimentje gegeven?',
    'Heb je vandaag een complimentje gekregen?',
    'Heb je vandaag een leugentje om bestwil verteld?',
    'Hoe lang ben je ooit achter elkaar wakker geweest?',
    'Hoe ziet je ideale vrije dag eruit?',
    'Hoe ziet jouw droomhuis eruit?',
    'Hoe ziet jouw perfecte dag eruit?',
    'Hoe ziet jouw perfecte date er uit?',
    'Hoe zou je dag eruit zien als je miljonair was?',
    'Hoeveel paar schoenen heb je?',
    'Hou je meer van honden of van katten?',
    'Houd je meer van zoet of van hartig?',
    'In welk boek zou jij de hoofdpersoon willen zijn?',
    'In welk land zou je het liefst willen wonen?',
    'In welk tijdperk had jij wel willen leven?',
    'In welk tijdperk zou je willen leven?',
    'In welk tv-programma zou jij te zien willen zijn?',
    'In welke eeuw had je graag willen leven?',
    'In welke sport zou jij een olympisch atleet willen zijn?',
    'Kook je liever zelf of bestel je liever eten?',
    'Maak je liever een bos – of een strandwandeling?',
    'Maakt geld gelukkig?',
    'Met welk beroemd persoon zou jij een dag willen ruilen?',
    'Met welke 5 foto’s zou je jouw leven omschrijven?',
    'Met welke beroemdheid zou jij een kopje thee willen drinken?',
    'Met welke oude bekende zou je graag weer eens afspreken?',
    'Met wie zou je het liefst dit kopje thee drinken?',
    'Met wie zou jij graag 24 uur willen doorbrengen?',
    'Met wie zou jij voor één dag willen ruilen?',
    'Naar welke dag in de geschiedenis zou je terug willen?',
    'Noem één raar ding aan jezelf?',
    'Om wie moest jij het hardst lachen?',
    'Op welke onbeantwoorde vraag wil je graag antwoord?',
    'Tegen wie kijk je op?',
    'Van welk boek zou je graag een verfilming zien?',
    'Van welke blunder heb je nog steeds nachtmerries?',
    'Van welke gebeurtenis zou je graag getuige zijn?',
    'Van welke kleine dingen word jij gelukkig?',
    'Van wie kreeg je allemaal vlinders in je buik?',
    'Van wie zou jij de gedachten willen lezen?',
    'Voor wie zou jij een fanclub oprichten?',
    'Waar ben je dankbaar voor in het leven?',
    'Waar ben je het meest bang voor?',
    'Waar ben jij het meest trots op?',
    'Waar heb je het laatst een foto van gemaakt?',
    'Waar heb je het meest spijt van?',
    'Waar heb je om gelachen vandaag?',
    'Waar kijk je als eerst naar bij een man/vrouw?',
    'Waar mag ik je \'s nachts voor wakker maken?',
    'Waar schaam je je het meest voor?',
    'Waar stoor jij je snel aan?',
    'Waar ter wereld voel jij je het meest comfortabel?',
    'Waar voel je jezelf het meest op je gemak?',
    'Waar word je blij van?',
    'Waar zie je jezelf over vijf jaar?',
    'Waar zou je beroemd mee willen zijn?',
    'Waar zou je het liefst 10 minuten gratis winkelen?',
    'Waar zou je morgen naar toe willen op vakantie?',
    'Waar zou je veel beter in willen zijn?',
    'Waar zou jij meer tijd aan willen besteden?',
    'Waarvoor kwam je vroeger vaak in de problemen?',
    'Wanneer heb je voor het laatst gehuild van het lachen?',
    'Wanneer komt het kind in jezelf weer boven?',
    'Wanneer vind je iemand oud?',
    'Was er een dag dat je gehuild hebt van geluk?',
    'Wat at je het liefst toen je klein was?',
    'Wat brengt een lach op jouw gezicht?',
    'Wat doe je het liefst doen op een regenachtige dag?',
    'Wat doe jij het liefst in het weekend?',
    'Wat eet je het liefst bij het ontbijt?',
    'Wat heb je altijd nog een keer tegen je ex willen zeggen?',
    'Wat heb je het laatst gekocht?',
    'Wat is de grootste gok die je ooit hebt genomen?',
    'Wat is de grootste prijs die je ooit gewonnen hebt?',
    'Wat is de laatste droom die je nog weet?',
    'Wat is de laatste film die je hebt gezien?',
    'Wat is de leukste mop die je ooit hebt gehoord?',
    'Wat is de meest vreemde plek waar je ooit geslapen hebt?',
    'Wat is de mooiste plek die je ooit hebt bezocht?',
    'Wat is de raarste droom die je ooit hebt gehad?',
    'Wat is het avontuurlijkste dat je ooit hebt gedaan?',
    'Wat is het beste advies dat je hebt gekregen?',
    'Wat is het gekste dat je ooit het gedaan?',
    'Wat is het gekste dat je vandaag hebt gedaan?',
    'Wat is het gekste dat je vandaag hebt gezien?',
    'Wat is het laatste dat je doet voor je gaat slapen?',
    'Wat is het leukste wat je geleerd hebt van je oma?',
    'Wat is het liefste dat je ooit voor iemand gedaan hebt?',
    'Wat is het liefste dat je ooit voor iemand gedaan hebt?',
    'Wat is het meest afgespeelde nummer in jouw playlist?',
    'Wat is het meest bijzondere wat iemand ooit voor je deed?',
    'Wat is het meest nutteloze advies dat je ooit hebt gekregen?',
    'Wat is het meest romantische dat jou is overkomen?',
    'Wat is het moeilijkste wat je ooit hebt gedaan?',
    'Wat is het mooiste cadeau dat je ooit kreeg?',
    'Wat is het ondeugendste dat je vroeger hebt uitgespookt?',
    'Wat is het slechtste cadeau dat je ooit gekregen hebt?',
    'Wat is iets dat nog niemand over jou weet?',
    'Wat is iets dat nog niemand van je weet?',
    'Wat is je allereerste herinnering?',
    'Wat is je aller-gekste bijbaan geweest?',
    'Wat is je droombaan?',
    'Wat is je ergste nachtmerrie?',
    'Wat is je favoriete ‘foute’ liedje?',
    'Wat is je favoriete gerecht?',
    'Wat is je favoriete quote?',
    'Wat is je favoriete snoep?',
    'Wat is je favoriete spel?',
    'Wat is je grootste droom?',
    'Wat is je meest favoriete kledingstuk?',
    'Wat is je minst favoriete baan die je ooit hebt gehad?',
    'Wat is jouw favoriete feestdag?',
    'Wat is jouw favoriete ijssmaak?',
    'Wat is jouw favoriete seizoen?',
    'Wat is jouw favoriete sprookje?',
    'Wat is jouw favoriete vakantieland?',
    'Wat is jouw meest dierbare plekje op aarde?',
    'Wat is jouw sterkste zintuig?',
    'Wat is jouw ultieme geluksmoment?',
    'Wat is voor jou het beste gevoel ter wereld?',
    'Wat kocht je van je eerste salaris?',
    'Wat maakt jou uniek?',
    'Wat mis je aan kind zijn?',
    'Wat staat er nog op je bucketlist?',
    'Wat vind jij het leukste aan man/vrouw zijn?',
    'Wat vind jij je beste eigenschap?',
    'Wat voor muziek heb je het laatst geluisterd?',
    'Wat was de laatste keer dat je de slappe lach had?',
    'Wat was de mooiste dag van je leven?',
    'Wat was het eerste waar je vanochtend aan dacht?',
    'Wat was het laatste waar je gisteren aan dacht?',
    'Wat was je grootste blunder?',
    'Wat wil je voor je volgende verjaardag bereikt hebben?',
    'Wat wilde je worden toen je klein was?',
    'Wat zou je absoluut niet kunnen missen?',
    'Wat zou je doen als je een carrière - switch kon maken?',
    'Wat zou je doen als je één dag 1.000 euro mocht opmaken?',
    'Wat zou je doen als je nooit meer hoefde te werken?',
    'Wat zou je doen als je onzichtbaar was?',
    'Wat zou je doen als je voor 1 dag van geslacht mag wisselen?',
    'Wat zou je graag nog eens willen doen?',
    'Wat zou je laatste avondmaal zijn?',
    'Wat zou je nog heel graag aan iemand willen vragen?',
    'Wat zou je op een dag willen doen dat je nog nooit hebt gedaan?',
    'Wat zou je uitvinden als alles te realiseren was?',
    'Wat zou je wensen als je drie wensen had?',
    'Wat zou jij het liefst tegen je jongere zelf zeggen?',
    'Wat zou jij veranderen als je minister-president was?',
    'Welk beroep zou je weleens voor een week willen proberen?',
    'Welk boek heb je het laatst gelezen?',
    'Welk dier geeft jouw persoonlijkheid het best weer?',
    'Welk dier zou je voor een dag willen zijn?',
    'Welk fictief karakter zou jij tot leven willen brengen?',
    'Welk geheim weet bijna niemand van jou?',
    'Welk goede voornemen heb jij ieder jaar opnieuw?',
    'Welk liedje neem je mee naar een onbewoond eiland?',
    'Welk muziek instrument zou je willen leren bespelen?',
    'Welk verhaal vertellen je vrienden altijd over jou?',
    'Welke 3 woorden omschrijven jou het best?',
    'Welke 3 voorwerpen zou jij meenemen naar een onbewoond eiland?',
    'Welke acteur zou de hoofdrol spelen in de film over jouw leven?',
    'Welke beroemdheid heb je ooit ontmoet?',
    'Welke beroemdheid zou je willen zijn?',
    'Welke bijnaam zou jij jezelf geven?',
    'Welke dag uit je leven zou je over willen doen?',
    'Welke dag zou je nog een keer willen beleven?',
    'Welke droom zou je heel graag zien uitkomen?',
    'Welke gave zou je willen hebben?',
    'Welke geur roept bij jou een herinnering uit je jeugd op?',
    'Welke karaktereigenschap zou je graag willen hebben?',
    'Welke keuken vind jij het lekkerst?',
    'Welke landen heb je allemaal bezocht?',
    'Welke leeftijd zou je het liefst voor altijd hebben?',
    'Welke liedjes zitten er in de soundtrack van jouw leven?',
    'Welke naam zou je jezelf geven als je deze mocht veranderen?',
    'Welke planeet zou jij het liefst bezoeken?',
    'Welke regel zou je het liefst willen breken?',
    'Welke stempels zou jij in je paspoort willen?',
    'Welke superkracht zou je het liefst willen hebben?',
    'Welke taal zou jij willen leren?',
    'Welke titel zou jij het boek over jouw leven geven?',
    'Welke uitdaging zou je nog eens willen aangaan?',
    'Welke voorwerpen uit je huis zou je meenemen bij een brand?',
    'Wie aan deze tafel heeft het meeste geluk?',
    'Wie heb je het laatst gebeld?',
    'Wie is de leukste persoon die je afgelopen jaar hebt leren kennen?',
    'Wie is jouw persoonlijke held?',
    'Wie neem je mee naar een onbewoond eiland?',
    'Wie uit het verleden zou je willen ontmoeten?',
    'Wie vond jij de meest vervelende leraar op school?',
    'Wie zou je voor één dag willen zijn?',
    'Zie je liever je grootste vraag beantwoord of je grootste wens vervuld?',
    'Zing je wel eens onder de douche?',
    'Zit je liever in de gevangenis of ben je liever dakloos?',
    'Zou je liever al je eten rauw eten of al je eten frituren?',
    'Zou je liever de loterij winnen of de perfecte baan vinden?',
    'Zou je liever gedachten kunnen lezen of onzichtbaar willen zijn?',
    'Zou je liever het verleden veranderen of de toekomst zien?',
    'Zou je liever voor een dag koning zijn of voor een dag weer kind?',
    'Zou je tien jaar korter willen leven in ruil om rijk te zijn?',
    'Zou je voor één dag het andere geslacht willen zijn?'
]


def random_question():
    return choice(questions)
